server:
  port: 7001

# Eureka配置
eureka:
  instance:
    hostname: localhost # Eureka服务端的实例名称
  client:
    register-with-eureka: false #  表示是否向Eureka注册中心注册自己
    fetch-registry: false # false 表示自己为注册中心
    service-url:  # 监控画面
       defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
       # 集群：http://localhost:7002/eureka/，http://localhost:7003/eureka/   #  （绑定其它eureka）