server:
  port: 8081

spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://101.35.161.29:3306/db01?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456

# Eureka的配置，服务注册到哪里
eureka:
  client:
    service-url:
       defaultZone: http://localhost:7001/eureka/   # 多个eureka用逗号
   instance:
     instance-id: springcloud-provider-dept8001   # 修改eureka上的默认描述信息

# info配置
info:
  company.name: springcloud.haohua.com